[Feature] Qual é a finalidade dos hosts
DanielHe4rt/backend4noobs pull request #7
Opened 2021-07-20 04:01 UTC by NicolasPereira

Realizei a criação do documento que fala sobre o que são os hosts.

Escrevi sobre os seguintes tópicos

- Entendendo o que é um host.
- Como funciona um serviço de hospedagem.
- Tipos de serviços
- Tipo de hosts

2021-07-22 01:47 UTC, DanielHe4rt requested changes

2021-07-22 01:47 UTC, DanielHe4rt commented on docs/1-fundamentos/6-hosts.md
> +## Tipo de hosts/hospedagens.
ajustar headers

2021-07-22 01:47 UTC, DanielHe4rt commented on docs/1-fundamentos/6-hosts.md
> +## Hospedagem compartilhada.
falta exemplos

2021-07-22 01:47 UTC, DanielHe4rt commented on docs/1-fundamentos/6-hosts.md
> +## VPS (Virtual Private Service - Servidor Virtual Privado)
falta exemplos de empresas que provê esse tipo de serviço

2021-07-22 01:47 UTC, DanielHe4rt commented on docs/1-fundamentos/6-hosts.md
> +## Servidor Dedicado.
falta exemplos de empresas que provê esse tipo de serviço

2021-07-22 02:04 UTC, NicolasPereira commented on docs/1-fundamentos/6-hosts.md
> +## Tipo de hosts/hospedagens.
Qual seria o jeito corredo da headers?

2021-12-14 13:51 UTC, DanielHe4rt approved these changes

2021-12-14 13:51 UTC, merged